2025-10-21 18:39:47,345 INFO    Thread-34 (_run_job):3226244 [wandb_init.py:setup_run_log_directory():705] Logging user logs to /home/wzseu/JJC_project/wls_33/wandb/run-20251021_183947-04sz9guu/logs/debug.log
2025-10-21 18:39:47,345 INFO    Thread-34 (_run_job):3226244 [wandb_init.py:setup_run_log_directory():706] Logging internal logs to /home/wzseu/JJC_project/wls_33/wandb/run-20251021_183947-04sz9guu/logs/debug-internal.log
2025-10-21 18:39:47,345 INFO    Thread-34 (_run_job):3226244 [wandb_init.py:init():832] calling init triggers
2025-10-21 18:39:47,345 INFO    Thread-34 (_run_job):3226244 [wandb_init.py:init():837] wandb.init called with sweep_config: {'batch_size': 16, 'bias_scale': 3, 'data_dir': 'data/windows_ieee33', 'device': 'cuda', 'epochs': 100, 'hidden': 256, 'lambda_op': 1, 'lambda_pf': 1, 'lambda_smooth': 0.01, 'lambda_wls_reg': 1, 'layers': 2, 'lr': 0.001, 'nhead': 4, 'tag': 'W24', 'use_mask': False, 'w_temp_th': 0.01, 'w_temp_vm': 0.01}
config: {'batch_size': 16, 'bias_scale': 3, 'data_dir': 'data/windows_ieee33', 'device': 'cuda', 'epochs': 100, 'hidden': 256, 'lambda_op': 1, 'lambda_pf': 1, 'lambda_smooth': 0.01, 'lambda_wls_reg': 1, 'layers': 2, 'lr': 0.001, 'nhead': 4, 'tag': 'W24', 'use_mask': False, 'w_temp_th': 0.01, 'w_temp_vm': 0.01, '_wandb': {}}
2025-10-21 18:46:54,583 INFO    Thread-34 (_run_job):3226244 [wandb_run.py:_finish():2275] finishing run a530029885-southeast-university/gm-se-sweep/04sz9guu
2025-10-21 18:46:54,583 INFO    Thread-34 (_run_job):3226244 [wandb_run.py:_atexit_cleanup():2474] got exitcode: 0
2025-10-21 18:46:54,584 INFO    Thread-34 (_run_job):3226244 [wandb_run.py:_restore():2456] restore
2025-10-21 18:46:54,584 INFO    Thread-34 (_run_job):3226244 [wandb_run.py:_restore():2462] restore done
2025-10-21 18:46:56,789 INFO    Thread-34 (_run_job):3226244 [wandb_run.py:_footer_sync_info():3872] logging synced files
2025-10-21 18:47:01,555 INFO    wandb-AsyncioManager-main:3226244 [service_client.py:_forward_responses():80] Reached EOF.
2025-10-21 18:47:01,555 INFO    wandb-AsyncioManager-main:3226244 [mailbox.py:close():137] Closing mailbox, abandoning 1 handles.
